# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(665, 450)
        MainWindow.setMinimumSize(QtCore.QSize(640, 420))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 621, 81))
        self.groupBox.setObjectName("groupBox")
        self.Path_Open_Button = QtWidgets.QPushButton(self.groupBox)
        self.Path_Open_Button.setGeometry(QtCore.QRect(550, 20, 61, 21))
        self.Path_Open_Button.setObjectName("Path_Open_Button")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label.setObjectName("label")
        self.Address_Bar = QtWidgets.QLineEdit(self.groupBox)
        self.Address_Bar.setGeometry(QtCore.QRect(40, 20, 501, 20))
        self.Address_Bar.setObjectName("Address_Bar")
        self.Text_Saving_Check_Box = QtWidgets.QCheckBox(self.groupBox)
        self.Text_Saving_Check_Box.setGeometry(QtCore.QRect(40, 50, 121, 17))
        self.Text_Saving_Check_Box.setObjectName("Text_Saving_Check_Box")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 621, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 60, 605, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Classification_Progress_Bar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.Classification_Progress_Bar.setProperty("value", 24)
        self.Classification_Progress_Bar.setObjectName("Classification_Progress_Bar")
        self.verticalLayout_5.addWidget(self.Classification_Progress_Bar)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Process_Status_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Process_Status_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Process_Status_Label.setObjectName("Process_Status_Label")
        self.verticalLayout_2.addWidget(self.Process_Status_Label)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 20, 601, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.Classification_Start_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Classification_Start_Button.setMaximumSize(QtCore.QSize(70, 25))
        self.Classification_Start_Button.setObjectName("Classification_Start_Button")
        self.horizontalLayout.addWidget(self.Classification_Start_Button)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 250, 621, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 19, 603, 111))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Result_Table = QtWidgets.QTableWidget(self.verticalLayoutWidget_5)
        self.Result_Table.setMinimumSize(QtCore.QSize(601, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Result_Table.setFont(font)
        self.Result_Table.setAlternatingRowColors(False)
        self.Result_Table.setShowGrid(True)
        self.Result_Table.setColumnCount(7)
        self.Result_Table.setObjectName("Result_Table")
        self.Result_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Result_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 127))
        self.Result_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Result_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Result_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Result_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Result_Table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Result_Table.setHorizontalHeaderItem(6, item)
        self.Result_Table.horizontalHeader().setCascadingSectionResizes(False)
        self.Result_Table.horizontalHeader().setDefaultSectionSize(60)
        self.Result_Table.horizontalHeader().setMinimumSectionSize(20)
        self.Result_Table.horizontalHeader().setStretchLastSection(False)
        self.Result_Table.verticalHeader().setCascadingSectionResizes(False)
        self.Result_Table.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout_6.addWidget(self.Result_Table)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 665, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Import"))
        self.Path_Open_Button.setText(_translate("MainWindow", "Open"))
        self.label.setText(_translate("MainWindow", "Path:"))
        self.Text_Saving_Check_Box.setText(_translate("MainWindow", "Save the Plant Text"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Classification"))
        self.Process_Status_Label.setText(_translate("MainWindow", "Status "))
        self.Classification_Start_Button.setText(_translate("MainWindow", "Start"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Results"))
        item = self.Result_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.Result_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Class"))
        item = self.Result_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "انسانی"))
        item = self.Result_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "فنی"))
        item = self.Result_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "هنر"))
        item = self.Result_Table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "پایه"))
        item = self.Result_Table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "پزشکی"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

